name: Browser Tests

on:
  workflow_dispatch:
  schedule:
    # weekly build
    - cron:  '0 1 * * 0'
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'LICENSE'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  tests:
    name: Tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        browser: [chrome, firefox] # must be lowercase
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4

    # https://stackoverflow.com/a/57948488
    - name: set browser
      run:   |
            if [ "$RUNNER_OS" == "Linux" ]; then
                  echo "PUPPETEER_PRODUCT=${{ matrix.browser }}" >> $GITHUB_ENV
            elif [ "$RUNNER_OS" == "Windows" ]; then
                  echo "PUPPETEER_PRODUCT=${{ matrix.browser }}" >> $env:GITHUB_ENV
            else
                  echo "$RUNNER_OS not supported"
                  exit 1
            fi
      shell: bash
    - uses: nick-fields/retry@v2
      name: npm ci
      with:
        timeout_seconds: 300
        max_attempts: 3
        retry_on: error
        command: npm ci
    - uses: nick-fields/retry@v2
      name: npm run ui_test
      with:
        timeout_seconds: 300
        max_attempts: 3
        retry_on: error
        command: npm run ui_test
    - uses: actions/upload-artifact@v4
      with:
        name: screenshots-${{ matrix.os }}-${{ matrix.browser }}
        path: screenshots\\*.png
