# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Unit tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: [ master ]

jobs:
  Test:
    runs-on: windows-latest

    strategy:
      matrix:
        browser: ['Chrome', 'Firefox']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: npm install
      env:
        PUPPETEER_PRODUCT: ${{ matrix.browser }}
    - run: npm test
